name: FancyFishing
version: 1.0
main: com.fancyfishing.FancyFishing
api-version: 1.13
commands:
  ff:
    description: Main command for FancyFishing plugin
    usage: /<command> [gui|catcher|reload|help]
    permission: fancyfishing.admin
    permission-message: You don't have permission to use this command!

permissions:
  fancyfishing.admin:
    description: Allows access to all FancyFishing commands
    default: op